### ISSUE TITLE
s3-like compatibility

### ISSUE THREAD

**Issue by zifeo** [protomaps/go-pmtiles#112]
while gocloud seems to [support](https://github.com/google/go-cloud/blob/master/internal/website/content/howto/blob/_index.md?plain=1#L262) `s3ForcePathStyle=true`, it does not seem possible to use it with pmtiles:
```
2024/01/04 00:45:10 main.go:128: Failed to create new server, open bucket s3://REDACTED?awssdk=v2&endpoint=REDACTED&region=us-east-1&s3ForcePathStyle=true: unknown query parameter "s3ForcePathStyle"
```

**Comment by bdon** [comment]
If you are inputting the URLs can you use virtual host-style URLs instead? AWS has been trying to deprecate path style URLs for a while https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access so it seem like they should be 1:1 equivalent.

**Comment by zifeo** [comment]
@bdon Thanks for getting back, unfortunately our storage provider does not offer virtual ones, only path style are supported.

**Comment by bdon** [comment]
Which storage provider or storage engine is this so others can reproduce?

**Comment by zifeo** [comment]
@bdon Openstack Swift, but I suppose you can also use minio to replicate.

**Comment by bdon** [comment]
PR here: https://github.com/protomaps/go-pmtiles/pull/113

Currently we force the use of awssdkv2, but v1 is necessary to support those flags and work with Minio. Defaulting to v1 shouldn't have any functional impact. The alternative is to add more storage implementation-specific logic to go-pmtiles but that would defeat the purpose of using the gocloud abstraction. 

Aligns with suggested way of using Minio in gocloud docs: https://gocloud.dev/howto/blob/#s3-compatible

**Comment by bdon** [comment]
I've merged it into `main`, please see if it fixes the issue and I'll make a minor release.

**Comment by zifeo** [comment]
@bdon confirmed, thanks a lot!

**Comment by bdon** [comment]
Released in https://github.com/protomaps/go-pmtiles/releases/tag/v1.12.0

**Comment by bdon** [comment]
FYI, AWS is putting aws-sdk-go v1 into maintenance mode; v2 will be the default going forward: https://github.com/google/go-cloud/releases/tag/v0.39.0

For the next minor version I am bumping the gocloud version

**Comment by zifeo** [comment]
@bdon Thanks for letting me know, what is the expect change? It seems unclear to me

**Comment by bdon** [comment]
Based on those release nodes Gocloud will be removing aws-sdk-v1 in early 2025. 

The AWS SDK V2 definitely supports forcing path-style S3 buckets, not quite sure how it's exposed through gocloud S3 connection strings.

**Comment by bdon** [comment]
1.22 defaults to awsv2: https://github.com/protomaps/go-pmtiles/releases/tag/v1.22.0

**Comment by zifeo** [comment]
@bdon upgraded and it worked out of the box :)
