### ISSUE TITLE
convert Error parsing mbtiles 

### ISSUE THREAD

**Issue by inspirity** [protomaps/go-pmtiles#128]
I tried to convert some mbtiles into pmtiles and had this issue.

Failed to convert MBTiles to header JSON, strconv.ParseFloat: parsing " -24.42318646": invalid syntax

It appears that the issue is caused by the leading space in the Float.

**Comment by bdon** [comment]
MBTiles specifies the formatting of the bounds string: https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#content

Can you fix your program generating MBTiles?

**Comment by inspirity** [comment]
Thank you for your quick response.

I found the issue in the metadata.center value of the dB.
The coordinates had a space after the comma.
Once I removed the space the conversion worked perfectly.

With this workaround I can use third party mbtiles, thank you!

**Comment by bdon** [comment]
Please adjust the software that generates the MBTiles to have values that conform to the spec, without spaces. 

Otherwise we need to handle an arbitrary amount of variations, like multiple spaces, newlines, etc in string values.

**Comment by inspirity** [comment]
You are absolutely right.
But I'm not the producer of the charts. Those are openCPN charts for sailors.

https://chartlocker.brucebalan.com/

I have no clue which Tool they use to produce the mbtiles. I will contact them and trying to figure out. 
I

**Comment by dirkwa** [comment]
I have the same issue.  When I try to convert this extracted file 

https://download946.mediafire.com/nsgdrbjqjkngGxPA2m8-Dzhx2DOEkJlha2SmVNI7mqa1EPoTMjqQN9xa86m1AIrC_gNY9Sf1b-neiXDrJV-PQE4OuDX6lZ86xvFVTtEYPwoPQXlACsgbuhbqrevkray6PRj_Z7ofF6z8HtuwRXE_m_SCHOW_-Z_bNTylOOqM3xIG/722rc3rabytojt1/Fiji_TCL2407_Navionics.zip

i get 

` Failed to convert MBTiles to header JSON, strconv.ParseFloat: parsing " -16.56072370": invalid syntax`

**Comment by dirkwa** [comment]
> Thank you for your quick response.
> 
> I found the issue in the metadata.center value of the dB. The coordinates had a space after the comma. Once I removed the space the conversion worked perfectly.
> 
> With this workaround I can use third party mbtiles, thank you!

How can I do this? What tools to you use? TIA!

**Comment by bdon** [comment]
v1.25.3 now handles this: https://github.com/protomaps/go-pmtiles/releases/tag/v1.25.3
