### ISSUE TITLE
arm64 docker images

### ISSUE THREAD

**Issue by jonasengelmann** [protomaps/go-pmtiles#136]
Currently available docker images only support amd64. It would be great if arm64 images could be provided as well!

**Comment by bdon** [comment]
I attempted to add it in https://github.com/protomaps/go-pmtiles/pull/138 but it looks like it requires a different build process:

```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
```

Can you investigate a PR for doing this? (and as a bonus, pushing to multiple registries without duplication)

**Comment by bdon** [comment]
Looks like it worked:

https://github.com/protomaps/go-pmtiles/pkgs/container/go-pmtiles
https://hub.docker.com/repository/docker/protomaps/go-pmtiles/general

Let me know if it solves it for you! Closing issue for now.

**Comment by jonasengelmann** [comment]
Works great! Many thanks!
