### ISSUE TITLE
Feature Request: Env variables to set CLI opts

### ISSUE THREAD

**Issue by j** [protomaps/go-pmtiles#14]
It'd be great if I can configure options using environment variables to have deployments be easily managed via docker, etc.

```
PMTILES_PATH=https://storage.googleapis.com/my-tiles
PMTILES_CORS=*
PMTILES_CACHE=2000
```

**Comment by bdon** [comment]
What would be the benefit of doing this vs passing them via argument substitution eg "--cache=$PMTILES_CACHE" ?

**Comment by bdon** [comment]
Closing this in favor of passing env vars as arguments with `$VAR`.
