### ISSUE TITLE
Corrupted file 

### ISSUE THREAD

**Issue by Mtehabsim** [protomaps/go-pmtiles#144]
I installed PMTiles using brew and used it to convert a mbtiles to a pmtiles, but whenever I run any comand on the file it show the following error:
'2024/02/20 16:01:26 main.go:205: Failed to verify archive, Failed to create range reader for new.pmtiles, EOF'

What might be the issue? considering I tested that the mbfiles file I used has correct data and run perfectly

**Comment by bdon** [comment]
will be addressed in #143

**Comment by bdon** [comment]
should be fixed in 1.18
