### ISSUE TITLE
Fails to convert world map due to /tmp space limitations

### ISSUE THREAD

**Issue by protamail** [protomaps/go-pmtiles#153]
When converting mbtiles DB, a temporary file is used under /tmp. This is going to fail on many e.g. default linux setups where /tmp is mounted as a ram disk (tmpfs) where 100G space availability is just unrealistic. Should use the destination file directory for temporary storage instead or at least give such an option.

**Comment by bdon** [comment]
There is already a `--tmpdir` option.

**Comment by protamail** [comment]
Oh, OK, didn't see it in the help screen.
