### ISSUE TITLE
Invalid help comment for download command

### ISSUE THREAD

**Issue by sylvaingaudan** [protomaps/go-pmtiles#154]
Current is "Upload a local archive to remote storage" while the action is downloading a remote archive to a local file
Could be "Download a remote archive to a local storage"

https://github.com/protomaps/go-pmtiles/blob/7c37b2659ea317ed658e05e26f1007df63327539/main.go#L101

**Comment by bdon** [comment]
Download currently isn't implemented so please ignore this functionality for now.

**Comment by bdon** [comment]
Resolved by https://github.com/protomaps/go-pmtiles/commit/8d023e2c78ad69078649a0523f1279f4838f5095
