### ISSUE TITLE
change tmp file location

### ISSUE THREAD

**Issue by lauriemann** [protomaps/go-pmtiles#160]
format for specifying tmp directory in convert command is not shown in help output

**Comment by bdon** [comment]
```
pmtiles convert --help
Usage: main convert <input> <output>

Convert an MBTiles or older spec version to PMTiles.

Arguments:
  <input>     Input archive.
  <output>    Output PMTiles archive.

Flags:
  -h, --help                Show context-sensitive help.

      --force               Force removal.
      --no-deduplication    Don't attempt to deduplicate tiles.
      --tmpdir=STRING       An optional path to a folder for tmp data.
```

**Comment by lauriemann** [comment]
Sorry,  you are correct, it is there in the specific help output for the convert command, which we missed as we had been looking at the top-level help, but we figured it out from source code.  RTFM error on our part, as the last line does point at it!  Thanks for the response.

pmtiles --help
Usage: pmtiles <command>

Flags:
  -h, --help    Show context-sensitive help.

Commands:
  convert <input> <output>
    Convert an MBTiles or older spec version to PMTiles.

  show <path>
    Inspect a local or remote archive.

  tile <path> <z> <x> <y>
    Fetch one tile from a local or remote archive and output on stdout.

  extract <input> <output>
    Create an archive from a larger archive for a subset of zoom levels or geographic region.

  verify <input>
    Verify the correctness of an archive structure, without verifying individual tile contents.

  serve <path>
    Run an HTTP proxy server for Z/X/Y tiles.

  download --bucket=STRING <new-file>
    Upload a local archive to remote storage.

  upload --bucket=STRING <input> <key>
    Upload a local archive to remote storage.

  version
    Show the program version.

Run "pmtiles <command> --help" for more information on a command.
