### ISSUE TITLE
Intergration as a library

### ISSUE THREAD

**Issue by DmitriyVTitov** [protomaps/go-pmtiles#166]
I want to integrate `go-pmtiles` into my project as a library instead of using complete app as a server.
I'd like to be able to import Go package with HTTP handler that could serve tiles. Do you have such plans to implement separate library for PMTiles?

**Comment by bdon** [comment]
Another example: https://github.com/protomaps/go-pmtiles/blob/main/caddy/pmtiles_proxy.go#L49

**Comment by DmitriyVTitov** [comment]
@thisisaaronland @bdon Thanks!
