### ISSUE TITLE
ETags/Retry support for "pmtiles serve"

### ISSUE THREAD

**Issue by bdon** [protomaps/go-pmtiles#17]
Requires using https://gocloud.dev/concepts/as/

**Comment by msbarry** [comment]
I played around with this, looks like it's fairly straightforward to make it work for s3 at least:

```diff
-func (ba BucketAdapter) NewRangeReader(ctx context.Context, key string, offset, length int64) (io.ReadCloser, error) {
-       reader, err := ba.Bucket.NewRangeReader(ctx, key, offset, length, nil)
+func (ba BucketAdapter) NewRangeReader(ctx context.Context, key string, offset, length int64, etag string) (io.ReadCloser, string, error) {
+       reader, err := ba.Bucket.NewRangeReader(ctx, key, offset, length, &blob.ReaderOptions{
+               BeforeRead: func(asFunc func(interface{}) bool) error {
+                       var req *s3.GetObjectInput
+                       if len(etag) > 0 && asFunc(req) {
+                               req.IfMatch = &etag
+                       }
+                       return nil
+               },
+       })
        if err != nil {
-               return nil, err
+               return nil, "", err
+       }
+       resultEtag := ""
+       var resp *s3.GetObjectOutput
+       if len(etag) > 0 && reader.As(resp) {
+               resultEtag = *resp.ETag
        }
-       return reader, nil
+       return reader, resultEtag, nil
 }
```

How do you think it should handle when it detects the etag has changed? Clear the cache for every entry associated with this file and retry from the root?

**Comment by bdon** [comment]
> How do you think it should handle when it detects the etag has changed? Clear the cache for every entry associated with this file and retry from the root?

Yeah, with at most 1 retry allowed, otherwise a badly behaved storage system or http server could put it into a loop

> Or it could just return the etag and the caller handles the if-match logic

I would prefer to use `If-Match` on the request side if possible across all implementations, because checking ETags only on the response side doesn't work with intermediate caches (like the browser), and if archives shrink making a range request past the end of the new archive returns 416 Range not Satisfiable instead of 200 + new etag
