### ISSUE TITLE
Serving formats other than `.mvt`

### ISSUE THREAD

**Issue by KasiaKoz** [protomaps/go-pmtiles#181]
Hello!

I read in your readme that the tiles can be served in `.png` and other format as well as `.mvt`. My local server works fine for `.mvt` but if I try anything else I get `400` bad requests with "path mismatch: archive is type MVT (.mvt)" (for the same tiles).  I am missing something but I can't figure it out combing through the docs.

Running version `1.20.0` with a locally stored file which I extracted from https://maps.protomaps.com/builds/

**Comment by bdon** [comment]
The file format is static, and go-pmtiles does not do any conversion between formats. If you want to serve PNG tiles you need to generate PNGs and store them in the archive.
