### ISSUE TITLE
Update `pmtiles upload --help`

### ISSUE THREAD

**Issue by zstadler** [protomaps/go-pmtiles#194]
`pmtiles upload --help` has `<key>` as the second parameter, yet it seems that this is the remote name, as [the docs say](https://docs.protomaps.com/pmtiles/cli#upload).

The help text is:
```
Usage: pmtiles upload --bucket=STRING <input> <key>

Upload a local archive to remote storage.

Arguments:
  <input>
  <key>

Flags:
  -h, --help                 Show context-sensitive help.

      --max-concurrency=2    # of upload threads
      --bucket=STRING        Bucket to upload to.
```

Perhaps the help could use the term `<remote>` instead of `<key>`.

**Comment by zstadler** [comment]
I find the word "key" confusing, especially given the need to set the access and secret access keys.

IMO, the docs are much more clear, as the use the terms "INPUT" and "REMOTE":

> ### upload
> 
> Upload an archive to cloud storage.
> 
> ```bash
> # requires environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY credentials
> pmtiles upload INPUT.pmtiles REMOTE.pmtiles --bucket=s3://BUCKET_NAME
> ```

**Comment by bdon** [comment]
Good point, I didn't think of that conflict between the access key and the object key. what about `object_name`?

**Comment by zstadler** [comment]
I suggest "remote_name".
At the end of the day, this is the name by which the tile source will by accessed.

The word "object" could create a different confusion for anyone not familiar with cloud storage terminology, such as myself.

**Comment by bdon** [comment]
`remote_name` could also be confused as the name you give to the remote bucket instead of the remote object.

Do you want to open a PR?

**Comment by bdon** [comment]
Thanks, 1.22.2 is released.
