### ISSUE TITLE
Update `minzoom` when using `extract --minzoom=`

### ISSUE THREAD

**Issue by zstadler** [protomaps/go-pmtiles#197]
When using `go-pmtiles show --tilejson` on the results of `go-pmtiles extract --minzoom=7` the output has `"minzoom": 0` rather than  `"minzoom": 7`.

Interestingly, when using `go-pmtiles extract --maxzoom=`, the tilejson output contains the correct maxzoom.

**Comment by bdon** [comment]
Thanks, I released 1.22.3:

https://github.com/protomaps/go-pmtiles/releases/tag/v1.22.3
