### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by bdon** [protomaps/go-pmtiles#3]
Put go-pmtiles docker image on GitHub registry

**Comment by eddy-geek** [comment]
is the image public? How can I retrieve it? (I tried `podman pull ghcr.io/protomaps/go-pmtiles` without success).

**Comment by eddy-geek** [comment]
so, the following worked -- as indicated in https://github.com/protomaps/go-pmtiles/pkgs/container/go-pmtiles that I somehow missed on the right pane of github:

```sh
podman pull ghcr.io/protomaps/go-pmtiles:master
```

**Comment by bdon** [comment]
I've updated GitHub actions to correctly detect the `main` branch instead of `master` after renaming. So it should have an updated artifact on container registry now.
