### ISSUE TITLE
Problem compressed vector tiles in MBTiles

### ISSUE THREAD

**Issue by halset** [protomaps/go-pmtiles#30]
Used go-pmtiles to convert a MBTiles with compressed vector tiles. It did not work in maplibre. Then I made the MBTiles with uncompressed vector tiles and converted again. Then it worked just fine. Am I doing something wrong?

**Comment by bdon** [comment]
can you share your MBTiles dataset, or at least the values in the `metadata` table?

**Comment by halset** [comment]
The metadata tables are equal. I am unfortunately not able to share the MBTiles. Should I add a `compression` row?

Bad one:
```
sqlite> select * from metadata where name != 'url_template';
name|naviz
format|pbf
minzoom|2
maxzoom|13
```

Good one:
```
sqlite> select * from metadata where name != 'url_template';
name|naviz
format|pbf
minzoom|2
maxzoom|13
```

**Comment by halset** [comment]
Turns out, I had used zlib compression in the MBTiles, but I should have used gzip compression. Sorry for the noise.

**Comment by bdon** [comment]
@halset thanks for reporting back! The reason Gzip is supported instead of zlib, deflate, etc is to be readable directly in browsers. Is there a particular need addressed by using zlib? From what I understand Gzip is a header wrapper around a zlib payload.

**Comment by halset** [comment]
No special reason. Just an error on my side in the code I wrote to create MBTiles. Fixed it now so my future MBTiles are gzip and work with go-pmtiles. Thank you.
