### ISSUE TITLE
Cannot specify location of temporary file for convert

### ISSUE THREAD

**Issue by lseelenbinder** [protomaps/go-pmtiles#32]
If your `/tmp` is mounted on a separate partition that doesn't have enough space to hold the pmtiles, the conversion of a mbtiles can never succeed.

**Comment by thisisaaronland** [comment]
I have a working branch to specify a custom directory for temp files here:

https://github.com/sfomuseum/go-pmtiles/tree/tmp

I am just doing some final testing and, barring any gotchas, will submit a PR.

**Comment by bdon** [comment]
Did some cleanup and released v2.0.0:

https://github.com/protomaps/go-pmtiles/releases/tag/v2.0.0

convert now takes a `--tmpdir=TMPDIR` option.
