### ISSUE TITLE
Add `pmtiles` to homebrew for easy installation - needs more GitHub stars and watchers

### ISSUE THREAD

**Issue by yuletide** [protomaps/go-pmtiles#39]
Makes it much easier to keep things up to date

https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
https://docs.brew.sh/Formula-Cookbook
Here's the tippecanoe formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tippecanoe.rb

Since this is open source it should be acceptable in `homebrew-core`: https://docs.brew.sh/Acceptable-Formulae

edit: looks like there's even a tool for this: https://jkawamoto.github.io/fgo/ and `goreleaser` also can generate a formula: https://goreleaser.com/customization/homebrew/

**Comment by kevinschaul** [comment]
This formula seems to be working, but anyone have edits before I open a PR to homebrew? https://github.com/kevinschaul/homebrew-core/blob/master/Formula/pmtiles.rb

**Comment by bdon** [comment]
@kevinschaul thanks for opening this PR in Homebrew! FYI I'm tentatively thinking about going back to the 1.x versioning (without any SemVer guarantee) because of problems introduced related to go modules via 2.x : do you think you could change the PR to point to the 1.7.0 release?

**Comment by kevinschaul** [comment]
@bdon No problem, I just switched it to the 1.7.0 release.

Unfortunately the formula is failing a brew test for not being popular enough:

```
* GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

But in the meantime, pmtiles can be installed with: `brew install kevinschaul/homebrew-core/pmtiles`

**Comment by bdon** [comment]
@kevinschaul great! so a note for anyone observing this GitHub issue, star or watch the repo so we can get it past the threshold!

**Comment by bdon** [comment]
@kevinschaul with >80 stars now we should pass this test: 

https://github.com/Homebrew/brew/blob/fbbcb9700c6a6ee71d9bd66f80c59d21265ffc8c/Library/Homebrew/utils/shared_audits.rb#L98

**Comment by kevinschaul** [comment]
Nice! Just submitted the PR: https://github.com/Homebrew/homebrew-core/pull/123227

**Comment by kevinschaul** [comment]
... and it should be merged!

`brew install pmtiles` should be working now.

**Comment by bdon** [comment]
Great! I guess we'll need to update Homebrew manually each time we release, but we'll deal with that when we get there.

**Comment by yuletide** [comment]
Works for me! This is great
