### ISSUE TITLE
Combine pmtiles files

### ISSUE THREAD

**Issue by jackiescanlon** [protomaps/go-pmtiles#45]
I'd like to combine two (or more) `.pmtiles` files. Browsing the docs I don't see a way to do this.

As a workaround I also considered converting the `.pmtiles` files back to `.mbtiles` files and using https://github.com/mapbox/tippecanoe 's `tile-join` tool to join them into a single `.mbtiles` file, and then back to a `.pmtiles` file. But I don't see a way to convert `.pmtiles` to `.mbtiles`.

Let me know if I'm missing something. Otherwise its just a feature request. Thank you!

**Comment by bdon** [comment]
Can you try using `tile-join` with multiple PMTiles inputs from https://github.com/felt/tippecanoe ?

This task requires deserializing vector tile PBFs so it's a little more sophisticated than `go-pmtiles` offers right now, but tippecanoe should handle it.

**Comment by jackiescanlon** [comment]
Ah, thanks for point me to that (I see now that felt/tippecanoe is the repo referenced in the protomaps documentation, not _mapbox_/tippecanoe :facepalm: ). That worked for me! Mostly - it only works for `.pmtiles` v3, and I have some old tiles from v2 that I was hoping to combine.

Do you know if there's any tool to convert v2 tiles to v3? Or is my best bet to just pull them off of protomaps.com again?

**Comment by bdon** [comment]
Yes, you can use `go-pmtiles` to upgrade v2:

`pmtiles convert v2.pmtiles v3.pmtiles`

**Comment by jackiescanlon** [comment]
Thank you so much!
