### ISSUE TITLE
writer improvements

### ISSUE THREAD

**Issue by bdon** [protomaps/go-pmtiles#5]
- [ ] support leafdir writing
- [x] support deduplication
- [ ] guarantee Hilbert optimization

**Comment by eddy-geek** [comment]
How much does #5 slow down conversion? If much, would you consider adding a flag to disable it, since it's not going to save much in some cases?

**Comment by bdon** [comment]
It should have almost no slow down, and in many cases will speed up because it skips writing duplicate tile entries. The duplication should use either FNV or xxHash which should be very fast relative to doing I/O.

**Comment by bdon** [comment]
Will be completed with v3 `convert` command which has been merged to master.
