### ISSUE TITLE
Missing row issue

### ISSUE THREAD

**Issue by tim-terry-otm** [protomaps/go-pmtiles#56]
How do i start to debug a 'Missing  row' error? Not much information is returned.

```
main.go:154: Failed to convert /home/ubuntu/tilemaker/planet.osm.mbtiles, Missing row
```
I'm using v1.8.0, with tilemaker v2.4.0

My script to generate the planet is....

```
aws s3 cp s3://osm-pds/2023/planet-230529.osm.pbf /data/planet-latest.osm.pbf
wget https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip -O /home/ubuntu/tilemaker/water-polygons-split-4326.zip
unzip -o water-polygons-split-4326.zip
ln -fs water-polygons-split-4326 coastline
wget https://osmdata.openstreetmap.de/download/land-polygons-complete-4326.zip -O /home/ubuntu/tilemaker/land-polygons-complete-4326.zip
unzip -o land-polygons-complete-4326.zip
ln -fs land-polygons-complete-4326 landcover
tilemaker --input /data/planet-latest.osm.pbf --output planet.osm.mbtiles --skip-integrity --store /tmp --compact
go-pmtiles convert planet.osm.mbtiles planet.pmtiles
```

**Comment by bdon** [comment]
can you upload your planet.osm.mbtiles to somewhere like cloudflare r2 temporarily so others can inspect it?

That looks like an unusual case because https://github.com/protomaps/go-pmtiles/blob/main/pmtiles/convert.go#L331 will only ask for Z/X/Y it just queried for.

**Comment by tim-terry-otm** [comment]
The planet file (100Gb) can be found here: https://pub-e66dcecf2b2c43dcbe1a1e7d43672645.r2.dev/bad-row-planet.osm.mbtiles
Dont mind investigating, just not sure where to start?

**Comment by bdon** [comment]
`select tile_row from tiles where zoom_level = 4 and tile_column = 8;`

```
-48
-1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
```

There tiles in your MBTiles file with negative values for Y (`tile_row`). Do you know where these come from?

**Comment by tim-terry-otm** [comment]
I just used the script above to create the tiles. i'll check to see if there are any similar reported issues with tilemaker regarding negative Y values....

**Comment by tim-terry-otm** [comment]
I ended up deleting the negative rows before running go-pmtiles. The tile data was empty for these rows.
