### ISSUE TITLE
Feature: pmtiles stats

### ISSUE THREAD

**Issue by bdon** [protomaps/go-pmtiles#70]
* coordinate with @msbarry on a rough CSV format that can be quickly turned into DuckDB
* needs to be produced in a single pass
* come to consensus on how duplicates are treated

Downstream requirements:
* joining with ("top 100k statistics")
* interactive visualization. We could write a very small web server utility that runs off the DuckDB file and spits out vector tiles or raster images: OR, we could create a drag-and-drop UI to run DuckDb in WebAssembly and produce tiles via addProtocol

**Comment by msbarry** [comment]
Startin a PR for planetiler tile stats output here: https://github.com/onthegomap/planetiler/pull/656

I think the relevant open questions to both implementations are:

> - [ ] what data to emit? Could be:
>   - tile-level (z,x,y->tile size)
>   - deduped-tile-level (z,x,y->id, id->tile sizes)
>   - layer-level (z,x,y,layer->layer sizes)
>   - or layer/attribute level (z,x,y,layer,attr->size that attribute contributes to layer)
> - [ ] what format to emit it in? (tsv.gz, duckdb, parquet, newline-delimited json)

**Comment by bdon** [comment]
Basic implementation on main now, discuss in https://github.com/onthegomap/planetiler/pull/656 and we'll follow the format in this project
