### ISSUE TITLE
Failed strconv.ParseFloat: parsing " 34.30084411"

### ISSUE THREAD

**Issue by freeExec** [protomaps/go-pmtiles#81]
When trying to convert mbtiles an error occurs:

`main.go:159: Failed to convert xxx.mbtiles, Failed to convert MBTiles to header JSON, strconv.ParseFloat: parsing " 34.30084411": invalid syntax`

The thing is that in the metadata the value for `center` was `28.33709717, 34.30084411, 18`, i.e. contained spaces between values.

**Comment by bdon** [comment]
[The MBTiles specification](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) describes `center` as:

> center (string of comma-separated numbers): The longitude, latitude, and zoom level of the default view of the map. Example: -122.1906,37.7599,11

Can you correct your MBTiles directly, or the process that creates that tileset metadata?

**Comment by freeExec** [comment]
Yes, I had to resort to sqlite to change the values. But I would like to simplify my life.

**Comment by bdon** [comment]
I am suggesting that `pmtiles convert` is working as intended - I'd prefer to reject data that does not conform to the MBTiles specification, otherwise we need to make all the parsing lenient against extra spaces, tabs, etc everywhere.

**Comment by bdon** [comment]
Please re-open if the suggested fix doesn't work for you, thanks!

**Comment by bdon** [comment]
v1.25.3 now handles this: https://github.com/protomaps/go-pmtiles/releases/tag/v1.25.3
