### ISSUE TITLE
Issues with this adding this package on caddyserver.com/download

### ISSUE THREAD

**Issue by bgiovand** [protomaps/go-pmtiles#94]
I'm having issues with this package on https://caddyserver.com/download specifically for the LinuxAMD64 platform but other platforms seem to be failing as well. Any insight?

Can always build up your own image with xcaddy but figure the download tool is path of least resistance to getting people up and running with what seems like a rad project. Might be worth the effort of looking into?

<img width="458" alt="image" src="https://github.com/protomaps/go-pmtiles/assets/179564/fc6448a6-c7e8-488e-b3f5-5d4749810965">

**Comment by bgiovand** [comment]
Seems to work now with latest update!

**Comment by bdon** [comment]
@bgiovand I don't have any insight into this since the Caddy downloads are a third party service. Let me know if it is working otherwise!
